### ISSUE TITLE
https://homl.info/colab3

### ISSUE THREAD

**Issue by jcmondt** [ageron/handson-ml3#113]
Why can I not go to https://homl.info/colab3 to find the solutions?

**Comment by ageron** [comment]
Hi @jcmondt ,
The solutions are located at the end of each notebook. For example, for chapter 1, just scroll down to the **Exercise Solutions** section at the end of the notebook (that notebook is [here](https://colab.research.google.com/github/ageron/handson-ml3/blob/main/01_the_machine_learning_landscape.ipynb)).
Hope this helps.
