### ISSUE TITLE
[IDEA] Consider changing variable name in chapter 5 notebook

### ISSUE THREAD

**Issue by tandao0909** [ageron/handson-ml3#120]
In the code cells you generated to solve the final exercise in chapter 5's notebook, I notice that you use `svm_clf` for the pipeline consists of `SVR`. I think it will be better if you rename it to `svm_reg`, as this is a pipeline for regression task, not classfication. <br>
I suggest this because I think you follow the convention to name a pipeline `*_reg` for a regression pipeline and `*_clf` for a classification pipeline. Please clarify me if I understand it wrong.

**Comment by ageron** [comment]
Good catch, thanks @tandao0909 ! Indeed, it was a copy&paste error, it should have been `svm_reg`, not `svm_clf` in that exercise. 👍
