### ISSUE TITLE
[QUESTION] CHAP18 Can't find the TF-Agent part

### ISSUE THREAD

**Issue by danny95928** [ageron/handson-ml3#121]
i can't find the code in chap18 about TF-Agent part.

**Comment by ageron** [comment]
Hi @danny95928 ,

You're right, I made the difficult decision to remove TF-Agents from the 3rd edition. There are several reasons for this:
1. The book was getting way too long, I had to cut some content
2. I had too many issues maintaining the code, it would break too often
3. Deep RL is a very broad topic, and to give it justice requires a whole book (there are some great ones out there), so the goal of chapter 18 is to teach the core principles and motivate readers to dig deeper.

Note that TF Agents code from the 2nd edition is still available at https://colab.research.google.com/github/ageron/handson-ml2/blob/master/18_reinforcement_learning.ipynb

Thanks for your understanding!
