### ISSUE TITLE
[BUG] folder "datasets" is missing from the repo

### ISSUE THREAD

**Issue by thomas-haslwanter** [ageron/handson-ml3#147]
When I tried
`git clone https://github.com/ageron/handson-ml3.git`
the directory-structure only included
`➜ gci -dir

    Directory: C:\Users\thomas\Downloads\handson-ml3

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           16-Jul-24  8:24 PM                .github
d----           16-Jul-24  8:24 PM                docker
d----           16-Jul-24  8:24 PM                images
`

**Comment by FriedrichFroebel** [comment]
Are you looking for https://github.com/ageron/data?

**Comment by thomas-haslwanter** [comment]
Yep, that is the one.
Thank you for the quick help!!
