### ISSUE TITLE
[BUG] Chapter 10 Preview not working

### ISSUE THREAD

**Issue by MatheusUema** [ageron/handson-ml3#164]
Thanks for helping us improve this project!

**Before you create this issue**
Please make sure you are using the latest updated code and libraries: see https://github.com/ageron/handson-ml3/blob/main/INSTALL.md#update-this-project-and-its-libraries

Also please make sure to read the FAQ (https://github.com/ageron/handson-ml3#faq) and search for existing issues (both open and closed), as your question may already have been answered: https://github.com/ageron/handson-ml3/issues

**Describe the bug**
Preview of Chapter 10 isn't working like the others
https://github.com/ageron/handson-ml3/blob/main/10_neural_nets_with_keras.ipynb

**Screenshots**
![image](https://github.com/user-attachments/assets/98473d7c-4d65-4b0d-b05b-dfc78a23077e)

**Comment by ageron** [comment]
Thanks for reporting this issue, @MatheusUema 👍 , I just fixed it.

Explanation: I had manually edited the `.ipynb` to remove some outdated outputs (I try to push localized changes in the notebooks to avoid blowing up the size of the repo), and I tested the notebook in Jupyter Lab, everything went well, so I pushed the notebook and tested it again on Colab, again everything went well! But it looks like Github's viewer is stricter, and it requires the `"outputs"` field in every code cell. In the future I'll also ensure that the notebook works well in GitHub's viewer.
