### ISSUE TITLE
[QUESTION] About the keyword argument "feature_names_out" of "FunctionTransformer" class

### ISSUE THREAD

**Issue by liganega** [ageron/handson-ml3#2]
The definition of `ratio_pipeline()` function in the [jupyter notebook of Chapter 2](https://github.com/ageron/handson-ml3/blob/main/02_end_to_end_machine_learning_project.ipynb) contains the following transformer:

```python
FunctionTransformer(column_ratio,
                    feature_names_out=[name]),
```

But the keyword `feature_names_out` is not listed as an argument in the [scikit-learn document ](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.FunctionTransformer.html) of `FunctionTransformer` class or its parent classes, and it's not clear how to understand it. 

Is that just for naming the transformer to be built or for any other pourpose? And why isn't it listed as a keyword argment of the `FunctionTransformer`'s constructor or of its parent classes'?

**Comment by FriedrichFroebel** [comment]
This is part of the upcoming changes for version 1.1, see https://github.com/scikit-learn/scikit-learn/commit/d23d589587ce5a6d5642018946511ef3818bcb32 which introduced this and https://scikit-learn.org/dev/modules/generated/sklearn.preprocessing.FunctionTransformer.html for the latest (development) docs.

**Comment by liganega** [comment]
@FriedrichFroebel: Thank you for the clarification. 

It's now clear how to understand the output of `preprocessing.get_feature_names_out()` function.
