### ISSUE TITLE
pydot requirement missing for keras "plot_model" functionality

### ISSUE THREAD

**Issue by immersinn** [ageron/handson-ml3#29]
Cloned repo and created new env from the environment.yml file today. When I ran through notebook, "10_neural_nets_with_keras",  the, "tf.keras.utils.plot_model(...)" cell failed with missing pydot requirement. Cell is marked as "extra code", and overall this doesn't really impact running through the notebook.

**Comment by ageron** [comment]
Good catch, thanks, I'll add it now to requirements.txt and environment.yml.

**Comment by ageron** [comment]
Trying to upgrade the libs while I'm at it, but I'm running into a little issue with the gym library: the API seems to have evolved a little bit, I'm getting errors with the latest version, so I'm fixing them. Hopefully won't be long.

**Comment by immersinn** [comment]
anything you'd like me to look into? dependency solving isn't my fav, but
I've had to slog through my fair-share, ha.

**Comment by ageron** [comment]
I haven't had time to fix the issues with the API changes in gym, so I ended up just updating all other libraries, and of course adding pydot, which fixes this issue.
Thanks a lot for your kind help, @immersinn !

**Comment by immersinn** [comment]
Awesome, thanks! Enjoying the book, thanks for all the hard work!

**Comment by ageron** [comment]
Thanks @immersinn ! FYI, I finally updated the notebook for chapter 18 to use the latest version of gym. There were quite a few breaking changes, including these:

![image](https://user-images.githubusercontent.com/76661/192167968-8ca177b4-ee01-4655-9ef1-030e3cbb2bf4.png)
