### ISSUE TITLE
Link is not working chapter 11[BUG]

### ISSUE THREAD

**Issue by amitmeel** [ageron/handson-ml3#30]
I'm currently reading the book from O'reilly website and in chapter 11 there is one link that is not working. It is under **Unsupervised Pretraining** header and when i'm trying to open the link [ https://homl.info/extra-anns](https://colab.research.google.com/github/ageron/handson-ml3/blob/main/extra_ann_architectures.ipynb) which redirects to https://colab.research.google.com/github/ageron/handson-ml3/blob/main/extra_ann_architectures.ipynb but this is not working and when i cheked the repo, I dont find it as well.

@ageron can you please update it.

**Comment by matthewmeyer** [comment]
The broken link is also in chapter 17 in reference to RBM's

**Comment by ageron** [comment]
Really sorry for the broken link. I've fixed this, the notebook is now available.
