### ISSUE TITLE
[QUESTION] Ridge regression cost function

### ISSUE THREAD

**Issue by liganega** [ageron/handson-ml3#4]
What's the right definition of the cost function for Ridge regression?

1) [The doc version](https://scikit-learn.org/dev/modules/generated/sklearn.linear_model.Ridge.html):

<img width="176" alt="ridge1" src="https://user-images.githubusercontent.com/2748863/162764875-1d76c7d5-5550-453d-a46d-ab44f660452c.png">

2) The book version:

<img width="198" alt="ridge2" src="https://user-images.githubusercontent.com/2748863/162764902-1e853e83-2347-4255-816e-7705307073be.png">

In the 2nd edition, 2 is used instead of m. Anyway, it's not obvious why with m.

**Comment by liganega** [comment]
For me it's  always been a mysterious whether it would help calculate faster/better to use any kind of constant factor such as 2, 1/m or 1/2 because, I think, theta_i would adapt to it anyway.

**Comment by liganega** [comment]
The confusing points makes suddenly sense when the Elastic Net is considered. The weight of alpha is different in each penalty. 

<img width="413" alt="화면 캡처 2022-04-18 235530" src="https://user-images.githubusercontent.com/2748863/163826974-82b0eb97-066b-475a-b4a2-8e4df1867a9f.png">

Althought now the confusion is gone, it is still not so obvious why so.

**Comment by UPstartDeveloper** [comment]
Hi @liganega, I think part of your answer was covered in [this issue](https://github.com/ageron/handson-ml2/issues/510#issuecomment-986159785) in the previous Hands-On ML repo.

**Comment by liganega** [comment]
Hi @UPstartDeveloper, thank you for your comment. It really solves my original question about adding 1/m factor to the Ridge case.

On the other hand, why the difference between 2*alpha and alpha in case of Elastic net is necessary is still not quite clear. Probably it just works better that way. That is, more weight on the Lasso part makes models work better.
