### ISSUE TITLE
scipy.stats.reciprocal is deprecated (at documentation level)

### ISSUE THREAD

**Issue by rleners** [ageron/handson-ml3#44]
In solution to exercice 10 of chapter 5, the random variable scipy.stats.reciprocal is used. It has been replaced (since v1.4.0), at least in Scipy's documentation, by scipy.stats.loguniform.

**Comment by ageron** [comment]
Good catch, thanks! The `reciprocal()` function still seems to work and does not give any deprecation warning, but indeed it's been removed from the documentation. I replaced it with `loguniform()`. 👍
